package api

import "time"

// since message data structure is going to be shared between the server and the client it will go here in api
// netID is going to be a more unique identifier for the users session
// SYS is like a ping from the server just to make sure the host is alive
// USER is a basic user sent text message
// JOIN_LEAVE is a message generated by the server saying that a user has left or joined the room

type Message struct {
	Type string 
	SessionID []byte
	SenderName string
	DateTime   time.Time
	Contents   []byte
}
